/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

import db.example.Tables
import db.example.tables.Author
import org.jooq.SQLDialect
import org.jooq.impl.DSL
import java.sql.DriverManager

class App

fun main() {
    val url = "jdbc:postgresql://localhost:5432/postgres?currentSchema=example"
    val user = "postgres"
    val password = "password"
    val conn = DriverManager.getConnection(url, user, password)
    conn.use { connection ->
        val dslContext = DSL.using(connection, SQLDialect.POSTGRES)
        val result = dslContext.select(Author.AUTHOR.ID, Author.AUTHOR.FIRST_NAME, Author.AUTHOR.LAST_NAME)
            .from(Tables.AUTHOR)
            .fetch()
        result.map { "id: ${it[Author.AUTHOR.ID]}, firstName: ${it[Author.AUTHOR.FIRST_NAME]}, lastName: ${it[Author.AUTHOR.LAST_NAME]}" }
            .forEach { println(it) }
    }
}
